### ISSUE TITLE
[FetchRedirected//UserAgentInvalid] Your report title

### ISSUE THREAD

**Issue by AntyOof** [tmxkn1/Microsoft-Reward-Chrome-Ext#116] opened 2023-04-20 13:52 UTC
What NOT to report:
- UserAgentInvalid errors that JUST occurred. Report this only if it repeatedly occurs over three days. Normally the issue will be hot-fixed without an update!

You can find the type of error by visiting chrome://extensions page and clicking the Errors next to this extension.

---------------------------------------------------------

**Describe the bug**
My plugin has not been working since a month ago. It keeps showing me the red err icon. I've reinstalled it for a few times but it still doesnt work in both my Chrome and Edge, but the plugin starts to work again in my Edge yesterday suddenly. The errors shown in Chrome are same as the ones showing in Edge, which are FetchRedirected and UserAgentInvalid. 

**Since when**
A month ago

**Screenshots**
Chrome
![image](https://user-images.githubusercontent.com/88095467/233383949-979abbd2-9ecc-4f6f-abe2-3cbcb4b6be29.png)
![image](https://user-images.githubusercontent.com/88095467/233386698-8929bab3-6514-44a2-83e7-407b3786bc88.png)
![image](https://user-images.githubusercontent.com/88095467/233386750-987275cc-e121-4678-9a8b-c97eee0387e3.png)
![image](https://user-images.githubusercontent.com/88095467/233386790-10229abe-a9fe-4815-bb37-ad4431fe0c2e.png)

Edge
![image](https://user-images.githubusercontent.com/88095467/233386467-1e3f58b8-b6b2-4858-ae66-924e3b33bfda.png)
![image](https://user-images.githubusercontent.com/88095467/233387019-88bc5c8e-0dca-45f4-a5b5-a846007d5b23.png)
![image](https://user-images.githubusercontent.com/88095467/233387057-fcff353e-8b3c-4b1f-99cc-e3c1f0b9ec88.png)
![image](https://user-images.githubusercontent.com/88095467/233387113-168ebc15-8aaa-481e-a73a-bc91a167ac8f.png)

**Your country**
Hong Kong(SAR), China(I totally support national secuirty)

**Your web browser and OS**
Chrome Windows 10, weirdly the one I installed in the Edge(on the same computer) started working again yesterday

**Additional context**
Thanks a lot for your plugin! Hope you'll be able to fix all the bugs :D

**Comment by tmxkn1** [comment] 2023-04-26 19:40
Hi, thanks for reporting the issue with details.

The issue is most likely related to your region as MS rewards use different sites in different regions, and permission to the sites need to be set correctly in the manifest. I will try to work out an elegant solution but for now I can offer you a quick fix if you can tell me the URL displayed in the address bar when you visit https://rewards.bing.com/

**Comment by tmxkn1** [comment] 2023-04-26 23:21
A duplicate of #100. Have you tried the solution suggested in it?

**Closed by tmxkn1** 2023-04-26 23:21 UTC
Labels: not doing searches
