### ISSUE TITLE
Icon Now Says "err" Always

### ISSUE THREAD

**Issue by UdderlyEvelyn** [tmxkn1/Microsoft-Reward-Chrome-Ext#18] opened 2021-12-12 23:35 UTC
I'm guessing things have changed, it now says "err" all the time, perhaps needs an update. I haven't looked into what has changed or how, not my area of expertise.

This is in Edge, Version 96.0.1054.34 (Official build) (64-bit).

**Comment by 666dsa666** [comment] 2021-12-23 15:32
Probably resolved by : https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/pull/21
Had the same issue, think it was a timeout caused by non-working mobile search.

**Closed** 2021-12-24 17:57 UTC
