### ISSUE TITLE
Does not work in China，just show "err" on the Action Button Badge

### ISSUE THREAD

**Issue by leftshine** [tmxkn1/Microsoft-Reward-Chrome-Ext#100] opened 2023-03-16 01:54 UTC
The reason maybe this：
In China open https://rewards.bing.com/welcome the link will report an error;
In China needs to jump directly to https://rewards.bing.com/?sign=1
Reference link：https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp/issues/72

**Comment by leftshine** [comment] 2023-03-16 02:02
append the debug info：
["Expected response status is within 200-299. Received response: FetchFailed::TypeError: Are we redirected? You probably haven't logged in yet.
InnerEx: TypeError: Failed to fetch
    at DailyRewardStatus.getUserStatusJson (chrome-extension://fggmegcnjjpioofcndpamehdobijogbk/status/DailyRewardStatus.js:72:30)
    at getDebugInfo (chrome-extension://fggmegcnjjpioofcndpamehdobijogbk/utility.js:83:27)
    at chrome-extension://fggmegcnjjpioofcndpamehdobijogbk/background.js:145:9
InnerEx: null",{"punchCards":[]}]

**Comment by tmxkn1** [comment] 2023-04-02 00:40
Thanks, I will try working out a solution for different regions.

**Comment by tmxkn1** [comment] 2023-04-26 23:18
A duplicate of #100

**Closed by tmxkn1** 2023-04-26 23:18 UTC
Labels: enhancement
